projects:
  mixmatchAppSyncAPI:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: tpmapqw3hbe73ihj4svpdmdi7u
        maxDepth: 2
extensions:
  amplify:
    version: 3
